### Test PayPal Payment
POST http://localhost:9024/api/users/1/pay/paypal
Content-Type: application/json

{
  "amount": 100.50,
  "currency": "USD",
  "recipient": "paypal@example.com"
}

### Test Stripe Payment
POST http://localhost:9024/api/users/1/pay/stripe
Content-Type: application/json

{
  "description": "Test Payment",
  "amount": 1000,
  "currency": "usd",
  "stripeEmail": "user@example.com",
  "stripeToken": "tok_visa"
}


### Test AliPay Payment
POST http://localhost:9024/api/users/1/pay/alipay
Content-Type: application/json

{
  "amount": 150.75,
  "currency": "CNY",
  "recipient": "alipay@example.com"
}

### Create User
POST http://localhost:9024/api/users
Content-Type: application/json

{
  "username": "newUser3",
  "email": "newuser3@example.com",
  "passwordHash": "encryptedPassword",
  "createdAt": "2024-01-11T10:00:00",
  "updatedAt": "2024-01-11T10:00:00"
}

###
### Supplier create 2
POST http://localhost:9024/api/v1/suppliers
Content-Type: application/json

{
  "supplierName": "UmiUni",
  "contactInfo": "Email: supplier5@example.com, Phone: +98766743210",
  "paypalClientId": "ARVTEXvfH2vehSfPi70J8wwYqyUK-zUfzbvvrQ3DQ3HzyGpyJJKroiZafyDy8xy7CCOMRLIjnZm-vmS8",
  "paypalClientSecret": "EDtRJPFl57bwygK882dnbTyEf4QsQzeLTbOL3nZjP46Vo-gd47-Xfm0cV2szj_h6I_iSSFVjO7ZJaGkk"
}

### Create Sales Order
POST http://localhost:9024/api/users/checkout/create-order
Content-Type: application/json

{
  "salesOrderId": null,
  "salesOrderSn": "SN12350",
  "customerId": 1,
  "supplierId": 1,
  "customerName": "John Doe",
  "customerEmail": "john.doe@example.com",
  "totalAmount": 19.00,
  "shippingAddress": "1234 Main St, Anytown, AT 12345",
  "billingAddress": "1234 Main St, Anytown, AT 12345",
  "orderStatus": "PENDING",
  "paymentMethod": "PayPal",
  "paymentProcessed": false,
  "expirationDate": "2024-01-19T15:00:00",
  "salesOrderDetail": [
    {
      "salesOrderDetailId": 456,
      "salesOrderSn": "SN12345",
      "skuCode": "SKU00124",
      "supplierId": 1,
      "quantity": 10,
      "unitPrice": 2.00,
      "discount": 0.10,
      "lineTotal": 19.00
    }
  ]
}

### Complete PayPal Payment
POST localhost:9024/api/users/checkout/complete-order
Content-Type: application/x-www-form-urlencoded

paymentId=PAYID-MWQ5UPY6JS463554L670574T&PayerID=3YGU5VNUABDU8&SupplierId=1

### Complete Order and Checkout
POST localhost:9024/api/users/checkout/complete-order?paymentId=PAYID-MWQY4UY5ED84563H1514780C&PayerID=3YGU5VNUABDU8&SupplierId=1
Content-Type: application/json

### Stripe Payment
POST http://localhost:9024/api/users/checkout/stripe/charge
Content-Type: application/json

{
  "token": "tok_visa",
  "salesOrder": {
    "salesOrderSn": "ORDER00568",
    "customerId": 1,
    "supplierId": 1,
    "customerName": "John Doe",
    "customerEmail": "johndoe@example.com",
    "orderDate": "2024-01-11T15:30:45",
    "totalAmount": 1.00,
    "shippingAddress": "123 Main St, Anytown, AT 12345",
    "billingAddress": "456 Secondary St, Othertown, OT 67890",
    "orderStatus": "PENDING",
    "paymentMethod": "PayPal",
    "paymentProcessed": false,
    "lastUpdated": "2024-01-11T10:00:00",
    "expirationDate": "2024-02-11T10:00:00"
  }
}